language: groovy
branches:
    except:
        - /^\\d+\\.\\d+\\.\\d+/
jdk:
    - openjdk8
cache:
    directories:
    - "$HOME/.m2"
    - "$HOME/.ivy2"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_install:
    - git config --global user.email "contact@saagie.com"
    - git config --global user.name "contact"
    - git remote set-url origin git@github.com:saagie/gradle-saagie-dataops-plugin.git
    - git config remote.origin.fetch refs/heads/*:refs/remotes/origin/*
    - openssl aes-256-cbc -K $encrypted_837e0722fe3d_key -iv $encrypted_837e0722fe3d_iv -in keys.tar.enc -out keys.tar -d
    - tar xvf keys.tar
    - mv id_rsa_travis ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - cp -fv config ~/.ssh/config
    - echo signing.password=$gpg_pass >> ~/.gradle/gradle.properties
    - echo nexusName=$SONATYPE_USERNAME >> ~/.gradle/gradle.properties
    - echo nexusPassword=$SONATYPE_PASSWORD >> ~/.gradle/gradle.properties
    - echo gradle.publish.key=$GRADLE_PUBLISH_KEY >> ~/.gradle/gradle.properties
    - echo gradle.publish.secret=$GRADLE_PUBLISH_SECRET >> ~/.gradle/gradle.properties
script:
    - ./gradlew test --stacktrace
    -   if [ ${TRAVIS_BRANCH} = "master" ]; then
            git checkout master;
            ./gradlew release -Prelease.useAutomaticVersion=true --stacktrace;
            ./gradlew closeAndReleaseRepository;
        else
            ./gradlew patch commitVersion -PbuildNumber=$TRAVIS_BUILD_NUMBER;
            ./gradlew uploadArchive --stacktrace;
        fi
env:
    global:
        - secure: lq8Na892LjfpLD642K36luhbhqAyz9LN0v0tIvXBF6SpNqLcym+oZYShs4FD2IB0+UI6KPqjhWbH82ebZjjo7on7wb0p/q+BO03b0ND7VQL0XkorgfDqIUUaKsxBTv6u52p7D0Pj+STIpiwv/UMjxL61Kbo7aSONcXemwnn7uFJzenl/7PaqvQNMTbNaHIa8RzHV3Rt/lv0Vv3ixyhfw84cAlqrh/9stkGJG0UsHKG+wWeXjOVOA0BXx61XT2KyVoRVfmMC2W9ubyADxw/cZ2A+ekejUuebCpn0w0wptWYOluk+uLmSgW4TNkqnPHRi9RIgcOOVqlH5e8bE2aqsNO6EJ471e4KQqLzjiWkHLXisHPtyYiMke9M2ubCBwchI6qLt7AswlShgunDD3FoVdnYMmvz0Odql0dyfdgtI7kuA8ub/AS8JEBs0wVeGv/S2Z2fL+0jdbGH7DQgrFeAulQaXIwLaxb1ai0d3ly03Hq7FBOhj8LOD8/MsqDrBXmv/cxgnTNSdA5I4LFMfLPSeuZ4mtPGoc23BbDnUGbTLzglplVyHPGortsfyxWl7JtrfNZeGs87BkQDRRmsgq5XYwB07tdzvPSDXHVyC3r9ZxwCNyqtFoxyY1ePZX6I9aflsQXvkQTt8bGtqyHUPU7qCCRFCNB+/tp1o6wPwQD64NYgI=
        - secure: Fp1tmexIPJ9GJQzXh4qiJRaku3+rhGNi23/9Nk3h8Dp1o23exjV6rGWWWDneD9U60JD6HCbjpSLWdNJyvt89VTXksDk8MHLbjzzKE1/EimxeN76Rjp4ilQHiH8eCX0JCzNyJbFFkeMGiWIaYsv2SEOHAZtdQFXnlFDJ9rsReZsU6IO6y83V8DugcLp6xmHNh0UvqE81fg89WT+Hd//TjvH5TJQMIkj4BI6AzNiMlUoro/NqI8yZfzQtOWl/vtRheqbN9BZWXUG4nBTXDAByzby5YIttJ34HrXA8WPPTJfEHt8Wm+xlU45kVeOfuZIg1bvfW3jG5clGfXdT1RkeLqHDEpmQkbsYoWxARozapqEFhDQ+XhhrkU6WwUsCF/T/ICvHvMWX+24Sb9FNkRavZnt5Awz5SaYMRc+WMhaPD2F/nUxwMvaTToAIgRyrhFawE9CwqF4MwDgRo8UAJ5Zkk2O+tnRMqfJm/hNRgDPzRn5dw7D5NIpZUolMVyzZOQsuu1SEg1xfWC3mU7j2YkQHWYWz3v545xX1UkrAWA/rEDFM34Wx5F9DLjF50eXEvsT31hwNTI8oba4IiM5grAeqh5kL49/FNrvd2HVhdbs+v+o/3sdFgaUSU85+T+CModmDBD4bVWVi2SW+97+UoluqwRZwR20An2YqM3oK9B/yOwH5k=
        - secure: Q8hcPeXayx5Y5FEkL+GN0RDlvmOArjTN/CMmoB1prhQFDXslWT1cqj7f97V/9e8A0l1dLyu9YFd5Z+ktzlCP1drTMXS781XinupU0cHiCE74HjdK7VqEtWVs6Rb4Ldk7ci+IbBFlZ4WUJxeqSJ/inPegrx3jhJfAwHtlbm9zImV7Ja8I2iptL2/vntiw9iaiD2WmqcawwiJg+O6+Tprg2+sJ3DKjtYTq6GvzQmENUuMpFmfXB66bngAbGj81RJH6DRxI5GUDthgxpABX7STDLdcteBKtaoc1o6sM6uNkEfL5wMg1WCwLFDeDdH0KdwcGx0ZT+xHu+S0vk2R/ATgf47Jy4sS5x8GUGnLQ0noQ9+CZTvIhEzxgHNDxtPuZYhPLYvUCW/poBX8XVFvHTnrkveIyZ9JX1Px1DN2tFnn93D+tFpuMxAe1Jo1CcL96WVJqbj84y+CMsRyYDgsXMDtM9nXXVW806np7F7LOD4s4fbAXPwAa/A8Y+KQRNrmc/tJ+QqJxxbeCGcvtqpqX1qIo+Wsg5GQLgeNrywnIMWx1o590Y4WKqrL9VXDlx/HHY08KtXh43wjsJS08K8Ku9Fd6Vy1oU79zMKEOLtLCY1orere6yMCkrcbQ03aVjBoRq44WsxlU8Z3+8C7AVd/25YU2U/vl0wpCs05Due709nJbGgo=
        - secure: e78stHjZipaZgQMkDa3xGXI8XRYeqaOk1Xnh3X2A9y/muERZC2o5lbzrnvu5P0+cKtrZd0yr+TUpSQsTwqrHVGY5aEi+mgZ0jDGqVaikP7Y9C0GjPFG2oo4R/AD5tNzPSqJSeq+mCaQEaiyL8KJajddTaPPy8b2/LJqsErrGRJQzpn6QCO/0eETCKSE8HDMiYB8fklMxze6B9gdMIlPKTL7o31sDKX47cYcjmD4ItnRB6uiCYCiezDL/p1DhEV2HvaiJIDWXg8hPaaQTjrA46VCrxVv+PKfhacTN0XRanCQUzyeZy3iomebvYadSjuy+bjywOU4p6V6LSHByMiNOj/r4GttlJvKPBV558CiUyVyPOArscqJKdXSNDA2qg6PRlLBZiWk4t/TnA3yaiQ+iqPF/Q9CKEhv8Pn5Sqr2QhEZUAkTsR7J+43NQN9cW4u4syN2ejw77sPLD9UW6/xzxsRGGm+szKzxf+e7KMyvUj/IR8v/j5mEfuUh5tI/HzgpMUkkuiS5Zpy2gAHQwGD9Sm5DiUWFoqaw0Ijx+CRaa3VedwTbJ/WSOg90Cbhk6aG0o1reCyeUb/FGIR/cL1BLB2HXfkWA8ekCBfuchJy4DiQlhRmMi6+KXTj3Y6F6JKKgKbgs0bYCtnLNM893f31uHG/tHtJW4rw2Sz9+roHCGwbo=
after_failure:
    - git status
    - git diff
